### ISSUE TITLE
TypeError raised when url starts with numeric digit and contains a null byte

### ISSUE THREAD

**Issue by arthurprevot** [john-kurkowski/tldextract#96] opened 2016-04-21 00:43 UTC
Hi. I came across this error. Shouldn't the library be resilient to that ? If so, I could take a stab at a PR. 

<img width="761" alt="screen shot 2016-04-20 at 8 33 12 pm" src="https://cloud.githubusercontent.com/assets/3277100/14694537/4171c750-0737-11e6-8ad0-a15654b42f46.png">

**Comment by john-kurkowski** [comment] 2016-04-21 15:00
Yeah. tldextract is supposed to be lenient with input. Most of the methods it calls are similarly lenient. But `socket.inet_aton` clearly has the opposite philosophy. 😃 

I'm thinking just catching `TypeError`? Not changing the caller's input? If callers send garbage in, they'll continue to get garbage out (see [this FAQ entry](https://github.com/john-kurkowski/tldextract#if-i-pass-an-invalid-url-i-still-get-a-result-no-error-what-gives)). But it shouldn't be an uncaught exception.

**Comment by mauricioabreu** [comment] 2016-05-27 18:29
I follow the philosophy of "catch exceptions when needed".
I am not sure that it is the case. Python is already raising an error. If we catch the exception, what we should do? Improve the message and raise the exception in the stack?

**Comment by john-kurkowski** [comment] 2016-05-30 20:29
I think the OP's desire is to swallow the exception. The method
`looks_like_ip` should return a bool for virtually all inputs. It should
almost never raise.

**Comment by mauricioabreu** [comment] 2016-07-12 00:19
So, the problem is that if we "deny" the exception, how the user is going to know what was wrong?
I know it is not of our concern to validate input but we can not hide exceptions either.

Am I missing something wrong?

**Comment by mauricioabreu** [comment] 2016-07-12 13:07
Anyways, I am willing to propose the fix to the problem. :D

**Comment by john-kurkowski** [comment] 2016-07-22 18:01
> how the user is going to know what was wrong?

That's the thing. There's nothing wrong with the input. It's a `str`. You can pass any `str` to tldextract. And it'll figure out some `ExtractResult` parsing for it.

**Comment by hangtwenty** [comment] 2016-08-23 17:19
Agree with @john-kurkowski that this is by design ... you don't want too much magic in this library. It's on the caller to clean input as desired before passing to `tldextract`.

**Comment by john-kurkowski** [comment] 2016-08-27 22:42
> Agree with @john-kurkowski that this is by design

Sorry, that's not what I meant. This is a bug. To summarize what I've been saying:

> ... it shouldn't be an uncaught exception ... There's nothing wrong with [@arthurprevot's] input. It's a `str`. You can pass any `str` to tldextract. And it'll figure out some `ExtractResult` parsing for it.

Put another way, here are my expected/actual in/outs.

| Input Type | Value | Expected Result | Actual |
|---|---|---|---|
| `str` | Something URL-like | `ExtractResult` | ✅ 
| `str` | A word | `ExtractResult` | ✅ 
| `str` | A single character | `ExtractResult` | ✅ 
| `str` | The empty string | `ExtractResult` | ✅ 
| `str` | An IP address | `ExtractResult` | ✅ 
| `str` | Something beginning with a null byte | `ExtractResult` | ❌  Uncaught exception
| `SomeOtherClass` | * | Uncaught exception | ✅ 

With that table, hopefully it's clearer where tldextract's inconsistency is.

I realize that's not the only way to do things. I'm flexible on this. But that's the way the library's been.

**Comment by hangtwenty** [comment] 2016-08-27 23:57
My bad for misinterpreting! That table clarifies a lot, thanks for taking the time 😄

**Comment by hangtwenty** [comment] 2016-08-27 23:59
Looking at those bottom two rows though. Is there really that much different between a `str`-with-a-null-byte and a `SomeOtherClass`?- Nevermind, to me it seems like a funky thing, kind of "not `tldextract`'s problem ... but really it's part of ASCII even. So I guess it has to be dealt with.

**Comment by hangtwenty** [comment] 2020-03-23 20:40
Closing because old (and it's a job for preprocessing)

**Closed by hangtwenty** 2020-03-23 20:40 UTC
Labels: help wanted, low priority: caller can pre/post-process
