### ISSUE TITLE
Potential dependency conflicts between tldextract and idna

### ISSUE THREAD

**Issue by NeolithEra** [john-kurkowski/tldextract#184] opened 2019-12-27 14:07 UTC
Hi, as shown in the following full dependency graph of  **_tldextract_**, **_tldextract_** requires **_idna *_** ， while the installed version of **_requests_**(2.22.0) requires _**idna >=2.5,<2.9**_.

According to Pip's _“first found wins”_ installation strategy, _**idna 2.8**_ is the actually installed version.  

Although the first found package version _**idna 2.8**_ just satisfies the later dependency constraint （_**idna >=2.5,<2.9**_), it will lead to a build failure once developers release a newer version of idna.

### Dependency tree--------
```

tldextract - 2.2.2
| +- idna(install version:2.8 version range:*)
| +- requests(install version:2.22.0 version range:>=2.1.0)
| | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- requests-file(install version:1.4.3 version range:>=1.4)
| | +- requests(install version:2.22.0 version range:>=1.0.0)
| | | +- certifi(install version:2019.9.11 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| | +- six(install version:1.13.0 version range:*)
| +- setuptools(install version:42.0.1 version range:*) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment] 2019-12-27 14:08
### Suggested Solution

1.	Fix your direct dependencies to be **_idna <2.9_**.
2.	Ask your upstream project **_requests_** to lose the version range of **_idna_** to be **_>=2.5_**.

@john-kurkowski Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by john-kurkowski** [comment] 2020-01-04 01:07
Dupe of #167.

**Closed by john-kurkowski** 2020-01-04 01:07 UTC
