### ISSUE TITLE
IDNA URLs with uppercase XN-- not split correctly

### ISSUE THREAD

**Issue by csfeathers** [john-kurkowski/tldextract#133] opened 2017-07-25 13:15 UTC
AFAICT from [RFC 3490](https://tools.ietf.org/html/rfc3490) the 'xn--' prefix check (apparently added in https://github.com/john-kurkowski/tldextract/issues/48) should be case insensitive:

> The ACE prefix for IDNA is "xn--" or any capitalization thereof.

Current behavior:

```
>>> import tldextract
>>> tldextract.extract('test.xn--p1ai')
ExtractResult(subdomain='', domain='test', suffix='xn--p1ai')
>>> tldextract.extract('test.Xn--p1ai')
ExtractResult(subdomain='test', domain='Xn--p1ai', suffix='')
>>> tldextract.extract('test.XN--p1ai')
ExtractResult(subdomain='test', domain='XN--p1ai', suffix='')
>>> tldextract.extract('test.xN--p1ai')
ExtractResult(subdomain='test', domain='xN--p1ai', suffix='')
```

**Comment by hangtwenty** [comment] 2019-03-04 00:48
@csfeathers thanks for reporting!

so, tldextract is **lenient** by design.  see the docs here: https://github.com/john-kurkowski/tldextract#if-i-pass-an-invalid-url-i-still-get-a-result-no-error-what-gives 

it does not, for example, call `.lower()` on the inputs because that is unnecessary processing for others (and there are users who call tldextract a helluva lot, so even though `.lower()` is a pretty mundane thing ... it should be avoided simply because unnecessary)

**Comment by hangtwenty** [comment] 2019-03-04 00:50
closing for now since it leniency is by-design and it is documented

**Comment by john-kurkowski** [comment] 2019-03-05 16:54
I think ignoring case here _would_ be the lenient thing.

**Closed** 2019-03-05 17:09 UTC
Labels: low priority: caller can pre/post-process, low priority: has trivial workaround, unicode or idna
