### ISSUE TITLE
[Errno 13] Permission denied: '/Library/Python/3.7/site-packages/tldextract/.tld_set'

### ISSUE THREAD

**Issue by myrainbowandsky** [john-kurkowski/tldextract#206] opened 2020-08-03 08:20 UTC
`unable to cache TLDs in file /Library/Python/3.7/site-packages/tldextract/.tld_set: [Errno 13] Permission denied: '/Library/Python/3.7/site-packages/tldextract/.tld_set'`

mac 10.15.5
python3.7
when using urlexpander

**Comment by john-kurkowski** [comment] 2020-08-04 18:04
This is an informational log? Is the library not working as expected? Sounds like a duplicate of #9. Expected when you don't have write permission to that file. See also [this FAQ entry](https://github.com/john-kurkowski/tldextract/tree/2.2.2#note-about-caching).

**Closed** 2020-09-07 22:46 UTC
