### ISSUE TITLE
blogspot.* recognized as ICANN TLD

### ISSUE THREAD

**Issue by kallleeeeh** [john-kurkowski/tldextract#112] opened 2016-11-09 16:56 UTC
Hi,
I noticed that `example.blogspot.com` is splitted to ` example blogspot.com`
It behaves the same in Python 3.5.2, but it works in Python 2.7.2

I wanted to delete the cache file in `/usr/local/lib/python3.5/dist-packages/tldextract/.tld_set` but it was not there. Updating with `tldextract -u` solved the problem.

**Comment by john-kurkowski** [comment] 2016-11-09 19:23
That blogspot.* parsing is expected if you use tldextract with the `include_psl_private_domains=True` arg. The default is `False`. 

Sounds like one of your caches was created with `include_private_psl_domains=True`?  `tldextract -u` is indeed the workaround. That will recreate the cache with the `False` arg. 

The cache inconsistency is a dupe of #66.

**Closed by john-kurkowski** 2016-11-09 19:23 UTC
