### ISSUE TITLE
Failed to parse punny coded URLs

### ISSUE THREAD

**Issue by hibare** [john-kurkowski/tldextract#164] opened 2019-07-11 17:19 UTC
Getting following error when parsing a punny coded URL.

>>> tldextract.extract('http://xn--dih35lxu47cdjah3bwa1rlv.xn--vi8hiv.ws/')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 379, in extract
    return TLD_EXTRACTOR(url)
  File "/venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 255, in __call__
    translations = [decode_punycode(label).lower() for label in labels]
  File "/venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 250, in decode_punycode
    return idna.decode(label.encode('ascii'))
  File "/venv/lib/python2.7/site-packages/idna/core.py", line 384, in decode
    result.append(ulabel(label))
  File "/venv/lib/python2.7/site-packages/idna/core.py", line 302, in ulabel
    label = label.decode('punycode')
  File "/venv/lib/python2.7/encodings/punycode.py", line 208, in decode
    res = punycode_decode(input, errors)
  File "/venv/lib/python2.7/encodings/punycode.py", line 195, in punycode_decode
    return insertion_sort(base, extended, errors)
  File "/venv/lib/python2.7/encodings/punycode.py", line 180, in insertion_sort
    base = base[:pos] + unichr(char) + base[pos:]
ValueError: unichr() arg not in range(0x10000) (narrow Python build)

**Comment by john-kurkowski** [comment] 2019-07-15 16:37
> narrow Python build

Sounds like #122

**Comment by john-kurkowski** [comment] 2019-08-19 19:23
Let's say it's a dupe of that. Focus discussion there. Reopen this if it's actually distinct.

**Closed by john-kurkowski** 2019-08-19 19:23 UTC
